import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { albersUsa, ringsToPath, VIEW_WIDTH, VIEW_HEIGHT } from '../src/projection.js';

/**
 * `src/projection.js` is a zero-dependency reimplementation of d3-geo's
 * `geoAlbersUsa`. These fixtures were generated by running d3-geo itself, so the
 * test pins the claim that the two agree rather than merely that the code is
 * self-consistent.
 */
const fixture = JSON.parse(readFileSync(new URL('./fixtures/albers-usa.json', import.meta.url), 'utf8'));

describe('albersUsa', () => {
  test('matches d3-geo on every fixture point', () => {
    for (const { name, lon, lat, expected } of fixture.points) {
      const actual = albersUsa([lon, lat]);

      if (expected === null) {
        assert.equal(actual, null, `${name} should project to null`);
        continue;
      }

      assert.ok(actual, `${name} unexpectedly projected to null`);
      const error = Math.hypot(actual[0] - expected[0], actual[1] - expected[1]);
      assert.ok(error < 1e-6, `${name}: ${error.toExponential(2)}px from d3-geo`);
    }
  });

  test('returns null well outside the United States', () => {
    assert.equal(albersUsa([0, 0]), null);
    assert.equal(albersUsa([139.7, 35.7]), null); // Tokyo
  });

  test('places the mainland, Alaska and Hawaii in their conventional panels', () => {
    const [sfX, sfY] = albersUsa([-122.42, 37.77]);
    const [akX, akY] = albersUsa([-149.9, 61.22]);
    const [hiX, hiY] = albersUsa([-157.86, 21.31]);

    // Alaska and Hawaii are insets in the lower left, beneath the mainland.
    assert.ok(akY > sfY, 'Alaska should sit below San Francisco on the plate');
    assert.ok(hiY > sfY, 'Hawaii should sit below San Francisco on the plate');
    assert.ok(akX < hiX, 'Alaska should sit to the left of Hawaii');
  });

  test('keeps the whole country inside the viewBox', () => {
    const corners = [
      [-124.73, 48.38], [-67.0, 44.81], [-97.14, 25.96], [-80.19, 25.76],
      [-149.9, 61.22], [-157.86, 21.31], [-176.63, 51.88],
    ];
    for (const c of corners) {
      const [x, y] = albersUsa(c);
      assert.ok(x >= 0 && x <= VIEW_WIDTH, `x ${x} outside 0..${VIEW_WIDTH}`);
      assert.ok(y >= 0 && y <= VIEW_HEIGHT, `y ${y} outside 0..${VIEW_HEIGHT}`);
    }
  });

  test('is a projection, not a scaling — east is right and north is up', () => {
    const [westX] = albersUsa([-120, 40]);
    const [eastX] = albersUsa([-75, 40]);
    const [, northY] = albersUsa([-100, 48]);
    const [, southY] = albersUsa([-100, 30]);

    assert.ok(eastX > westX, 'eastward should increase x');
    assert.ok(northY < southY, 'northward should decrease y');
  });
});

describe('ringsToPath', () => {
  test('closes each ring and joins multiple rings into one path', () => {
    const d = ringsToPath([
      [[0, 0], [10, 0], [10, 10]],
      [[20, 20], [30, 20], [30, 30]],
    ]);
    assert.equal(d, 'M0,0L10,0L10,10ZM20,20L30,20L30,30Z');
  });

  test('drops degenerate rings that cannot enclose an area', () => {
    assert.equal(ringsToPath([[[0, 0], [1, 1]]]), '');
  });

  test('rounds coordinates to keep the committed basemap small', () => {
    const d = ringsToPath([[[1.23456, 2.34567], [3.1, 4.2], [5.9, 6.8]]], 1);
    assert.ok(d.startsWith('M1.2,2.3'), `got ${d}`);
  });
});

/**
 * The basemap is a build artefact, but it is committed, so a corrupted or
 * truncated rebuild should fail here rather than render as a broken map.
 */
describe('the committed basemap', () => {
  const basemap = JSON.parse(
    readFileSync(new URL('../data/us-basemap.json', import.meta.url), 'utf8'),
  );

  test('carries every county and every state', () => {
    assert.ok(basemap.counties.length > 3100, `only ${basemap.counties.length} counties`);
    assert.equal(basemap.states.length, 51);
  });

  test('every county has a five-digit FIPS and a non-empty path', () => {
    for (const county of basemap.counties) {
      assert.match(county.id, /^\d{5}$/, `bad FIPS ${county.id}`);
      assert.ok(county.d.startsWith('M'), `${county.name} has no path data`);
    }
  });

  test('county FIPS codes are unique', () => {
    assert.equal(new Set(basemap.counties.map((c) => c.id)).size, basemap.counties.length);
  });

  test('all geometry falls inside the declared viewBox', () => {
    assert.equal(basemap.viewBox, `0 0 ${VIEW_WIDTH} ${VIEW_HEIGHT}`);

    for (const county of basemap.counties) {
      for (const [, xs, ys] of county.d.matchAll(/(-?[\d.]+),(-?[\d.]+)/g)) {
        const x = Number(xs);
        const y = Number(ys);
        assert.ok(x >= -1 && x <= VIEW_WIDTH + 1, `${county.name} x=${x} escapes the viewBox`);
        assert.ok(y >= -1 && y <= VIEW_HEIGHT + 1, `${county.name} y=${y} escapes the viewBox`);
      }
    }
  });
});
